"""
Interpreter implementation for the toy programming language.

This module traverses and executes the Abstract Syntax Tree (AST)
generated by the parser. It evaluates expressions, processes statements,
and manages program state using a symbol table.

Key Features:
- Supports arithmetic, comparison, and logical operations
- Handles variables (declaration and assignment)
- Executes control flow constructs (if, while, for)
- Provides input/output functionality
- Includes runtime error handling via custom exceptions
- Optional execution tracing for debugging
- Colored terminal output for better visualization

Design:
The interpreter uses the visitor pattern, where each AST node type
has a corresponding visit method (e.g., visit_BinOp, visit_IfStatement).
This allows clean separation of logic for each language construct.

The symbol table stores variable names and their values during execution,
and helper methods ensure proper type handling and formatting.

Overall, this module acts as the execution engine of the compiler pipeline:
    AST → Interpreter → Program Output
"""

from ast_nodes import (
    Program,
    Block,
    Number,
    String,
    Variable,
    BinOp,
    UnaryOp,
    LetStatement,
    AssignStatement,
    PrintStatement,
    InputExpression,
    IfStatement,
    WhileStatement,
    ForStatement,
)
from errors import InterpreterError


class Color:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    MAGENTA = "\033[95m"
    RED = "\033[91m"
    BLUE = "\033[94m"


class Interpreter:
    def __init__(self, trace=False, color=True):
        self.symbol_table = {}
        self.trace = trace
        self.color = color

    def c(self, text, color_code):
        if self.color:
            return f"{color_code}{text}{Color.RESET}"
        return text

    def log(self, message):
        if self.trace:
            print(self.c(f"[trace] {message}", Color.MAGENTA))

    def visit(self, node):
        method_name = f"visit_{type(node).__name__}"
        method = getattr(self, method_name, self.no_visit_method)
        return method(node)

    def no_visit_method(self, node):
        raise InterpreterError(f"No visit method for {type(node).__name__}")

    def is_truthy(self, value):
        if isinstance(value, str):
            return len(value) > 0
        return value != 0

    def visit_Program(self, node: Program):
        self.log("Starting program execution")
        for stmt in node.statements:
            self.visit(stmt)
        self.log("Program execution finished")

    def visit_Block(self, node: Block):
        for stmt in node.statements:
            self.visit(stmt)

    def visit_Number(self, node: Number):
        return node.value

    def visit_String(self, node: String):
        return node.value

    def visit_Variable(self, node: Variable):
        if node.name not in self.symbol_table:
            raise InterpreterError(f"Undefined variable '{node.name}'")
        return self.symbol_table[node.name]

    def visit_UnaryOp(self, node: UnaryOp):
        value = self.visit(node.operand)

        if node.op == "PLUS":
            self.ensure_number(value, "Unary plus")
            return +value
        if node.op == "MINUS":
            self.ensure_number(value, "Unary minus")
            return -value
        if node.op == "NOT":
            return 0.0 if self.is_truthy(value) else 1.0

        raise InterpreterError(f"Unknown unary operator {node.op}")

    def visit_BinOp(self, node: BinOp):
        left = self.visit(node.left)
        right = self.visit(node.right)

        if node.op == "PLUS":
            if isinstance(left, str) or isinstance(right, str):
                return str(left) + str(right)
            self.ensure_number(left, "Addition")
            self.ensure_number(right, "Addition")
            return left + right

        if node.op == "MINUS":
            self.ensure_number(left, "Subtraction")
            self.ensure_number(right, "Subtraction")
            return left - right

        if node.op == "MULTIPLY":
            self.ensure_number(left, "Multiplication")
            self.ensure_number(right, "Multiplication")
            return left * right

        if node.op == "DIVIDE":
            self.ensure_number(left, "Division")
            self.ensure_number(right, "Division")
            if right == 0:
                raise InterpreterError("Division by zero")
            return left / right

        if node.op == "EQ":
            return 1.0 if left == right else 0.0
        if node.op == "NE":
            return 1.0 if left != right else 0.0
        if node.op == "LT":
            return 1.0 if left < right else 0.0
        if node.op == "LE":
            return 1.0 if left <= right else 0.0
        if node.op == "GT":
            return 1.0 if left > right else 0.0
        if node.op == "GE":
            return 1.0 if left >= right else 0.0

        if node.op == "AND":
            return 1.0 if self.is_truthy(left) and self.is_truthy(right) else 0.0
        if node.op == "OR":
            return 1.0 if self.is_truthy(left) or self.is_truthy(right) else 0.0

        raise InterpreterError(f"Unknown binary operator {node.op}")

    def visit_LetStatement(self, node: LetStatement):
        if node.name in self.symbol_table:
            raise InterpreterError(f"Variable '{node.name}' already declared")
        value = self.visit(node.expr)
        self.symbol_table[node.name] = value
        self.log(f"Declared {node.name} = {self.format_value(value)}")

    def visit_AssignStatement(self, node: AssignStatement):
        if node.name not in self.symbol_table:
            raise InterpreterError(
                f"Variable '{node.name}' must be declared with 'let' first"
            )
        value = self.visit(node.expr)
        self.symbol_table[node.name] = value
        self.log(f"Assigned {node.name} = {self.format_value(value)}")

    def visit_PrintStatement(self, node: PrintStatement):
        value = self.visit(node.expr)
        print(self.c(f"→ {self.format_value(value)}", Color.GREEN))

    def visit_InputExpression(self, node: InputExpression):
        prompt = ""
        if node.prompt is not None:
            prompt = self.format_value(self.visit(node.prompt))
        raw = input(self.c(prompt, Color.YELLOW))

        try:
            return float(raw) if "." in raw else float(int(raw))
        except ValueError:
            return raw

    def visit_IfStatement(self, node: IfStatement):
        condition_value = self.visit(node.condition)
        self.log(f"IF condition = {self.format_value(condition_value)}")
        if self.is_truthy(condition_value):
            self.visit(node.then_branch)
        elif node.else_branch is not None:
            self.visit(node.else_branch)

    def visit_WhileStatement(self, node: WhileStatement):
        iteration = 0
        while self.is_truthy(self.visit(node.condition)):
            iteration += 1
            self.log(f"WHILE iteration {iteration}")
            self.visit(node.body)

    def visit_ForStatement(self, node: ForStatement):
        self.visit(node.init)
        iteration = 0
        while self.is_truthy(self.visit(node.condition)):
            iteration += 1
            self.log(f"FOR iteration {iteration}")
            self.visit(node.body)
            self.visit(node.update)

    def ensure_number(self, value, context):
        if isinstance(value, str):
            raise InterpreterError(f"{context} requires numeric operands, got string")

    def format_value(self, value):
        if isinstance(value, float) and value.is_integer():
            return str(int(value))
        return str(value)

    def print_symbol_table(self):
        print(self.c("===== SYMBOL TABLE =====", Color.CYAN))
        if not self.symbol_table:
            print("(empty)")
            return
        for name in sorted(self.symbol_table.keys()):
            print(self.c(f"{name} = {self.format_value(self.symbol_table[name])}", Color.BLUE))